### ISSUE TITLE
Plugin Portal Submissions

### ISSUE THREAD

**Issue by octylFractal** [aSoft-Ltd/foundation#27]
Hi, Gradle developer here, we've received your submissions for some of these Gradle plugins but need to confirm some details with you. Unfortunately, the email associated with your Plugin Portal account is no longer receiving messages. Please reach out to us at `plugin-portal-support@gradle.com` so we can resolve this issue and allow you to publish your plugins.

**Comment by andylamax** [comment]
Aaaah, yes. We had changed our mailing servers due to some security reasons we had with our host.

We tried changing the portal email to no avail, but since we could still publish, it wasn't a big issue to us.

Will send email to you from `asoft@technologist.com`

**Comment by ljacomet** [comment]
We have received nothing so far, we will reject the pending submissions by the end of the week without news from you.
